In [1]:
import torch
import numpy as np
print(torch.__version__)

1.3.1


### torch 基本处理单元

In [18]:
# 返回的数组大小5x4的矩阵
print(torch.Tensor(5, 4))

#使用torch.tensor创建Tensor
print(torch.tensor([5,4]))

# 得到矩阵大小
a = torch.rand(5, 4)
print(a.size())

# numpy 类似的返回5x4大小的矩阵
print(np.ones((5, 4)))

# numpy 和 torch.Tensor 之间的转换
a = torch.rand(5, 4)
b = a.numpy()
print(b)

tensor([[0.0000, 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.2341, 0.7912]])
tensor([5, 4])
torch.Size([5, 4])
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[0.7671256  0.7900159  0.64528286 0.9908483 ]
 [0.5194284  0.40767384 0.6913311  0.39923298]
 [0.42957473 0.4920962  0.25962853 0.7982873 ]
 [0.56947637 0.0475288  0.11929905 0.3943758 ]
 [0.04406333 0.03385818 0.46141464 0.91640157]]


In [3]:
a = np.array([[3, 4], [3, 6]])
b = torch.from_numpy(a)
print(b)

tensor([[3, 4],
        [3, 6]])


运算和numpy类似

In [4]:
x = torch.rand(5, 4)
y = torch.rand(5, 4)
c = 3

In [5]:
print(c * x)
print(x + y)
print(x.add(y))

tensor([[1.4946, 1.3366, 1.2578, 1.8533],
        [2.2119, 0.7762, 0.4060, 2.2987],
        [0.6867, 0.6826, 1.0192, 2.0836],
        [1.6488, 0.4626, 2.3486, 1.5477],
        [2.5273, 1.5043, 1.6045, 2.6968]])
tensor([[1.2635, 0.7035, 1.2137, 1.0401],
        [1.3422, 1.0310, 0.8215, 1.2571],
        [0.5571, 0.5640, 0.8768, 1.4726],
        [1.5067, 0.5577, 1.4611, 0.8020],
        [0.9885, 0.9937, 1.0266, 1.5000]])
tensor([[1.2635, 0.7035, 1.2137, 1.0401],
        [1.3422, 1.0310, 0.8215, 1.2571],
        [0.5571, 0.5640, 0.8768, 1.4726],
        [1.5067, 0.5577, 1.4611, 0.8020],
        [0.9885, 0.9937, 1.0266, 1.5000]])


In [6]:
# 可以直接进行操作改变原对象，x+y或者x.add()并不会改变x，但是x.add_()则会对x进行改变
x.add_(y)

tensor([[1.2635, 0.7035, 1.2137, 1.0401],
        [1.3422, 1.0310, 0.8215, 1.2571],
        [0.5571, 0.5640, 0.8768, 1.4726],
        [1.5067, 0.5577, 1.4611, 0.8020],
        [0.9885, 0.9937, 1.0266, 1.5000]])

In [7]:
print(x)

tensor([[1.2635, 0.7035, 1.2137, 1.0401],
        [1.3422, 1.0310, 0.8215, 1.2571],
        [0.5571, 0.5640, 0.8768, 1.4726],
        [1.5067, 0.5577, 1.4611, 0.8020],
        [0.9885, 0.9937, 1.0266, 1.5000]])


In [19]:
# 将 torch.Tensor 放到 GPU 上
# 判断一下电脑是否支持GPU
torch.cuda.is_available()

False

In [9]:
a = torch.rand(5, 4)
# a = a.cuda()
print(a)

tensor([[0.4672, 0.1916, 0.8725, 0.4729],
        [0.8707, 0.8414, 0.2871, 0.3891],
        [0.1879, 0.5877, 0.1834, 0.1500],
        [0.6348, 0.0187, 0.2380, 0.1548],
        [0.2477, 0.8862, 0.2341, 0.7912]])


### torch 的自动求导功能
torch 和大部分框架一样有着自动求导功能，对象不再是 torch.Tensor，而是torch.autograd.Variable

本质上Variable和Tensor没有什么区别，不过Variable会放在一个计算图里面，可以进行前向传播和反向传播以及求导  

![1.png](../pics/autograd0.png)

里面的creator表示通过什么操作得到的这个Variable，grad表示反向传播的梯度

In [10]:
from torch.autograd import Variable

In [11]:
# requires_grad 表示是否对其求梯度，默认是False
x = Variable(torch.Tensor([3]), requires_grad=True)
y = Variable(torch.Tensor([5]), requires_grad=True)
z = 2 * x + y + 4

In [12]:
# 对 x 和 y 分别求导，默认只求一次导，如果要多次求导需要设置 retain_graph=True
z.backward()

In [13]:
# x 的导数和 y 的导数
print('dz/dx: {}'.format(x.grad.data))
print('dz/dy: {}'.format(y.grad.data))

dz/dx: tensor([2.])
dz/dy: tensor([1.])


### 神经网络部分

所依赖的主要是 torch.nn 和 torch.nn.functional

torch.nn 里面有着所有的神经网络的层的操作，其用来构建网络，只有执行一次网络的运算才执行一次

torch.nn.functional 表示的是直接对其做一次向前运算操作

In [14]:
from torch import nn
import torch.nn.functional as F

In [16]:
# 基本的网络构建类模板
class net_name(nn.Module):
    def __init__(self):
        super(net_name, self).__init__()
        # 可以添加各种网络层
        self.conv1 = nn.Conv2d(3, 10, 3)
        # 具体每种层的参数可以去查看文档
        
    def forward(self, x):
        # 定义向前传播
        out = self.conv1(x)
        return out